D_steps_per_G: 1
architecture: skip
aspect_ratio: 1.0
batchSize: 1
cache_filelist_read: false
cache_filelist_write: false
checkpoints_dir: ./checkpoints
cond_mod: true
continue_train: false
crop_size: 128
d_reg_every: 16
dataroot: ./datasets/cityscapes/
dataset_mode: testimage
dataset_mode_train: coco
debug: false
display_freq: 101
dlatent_size: 512
dropout_rate: 0.5
factor: null
factor_d: 5
factor_i: 0
fmap_base: 16384
fmap_decay: 1.0
fmap_max: 512
fmap_min: 1
freeze_D: false
fused_modconv: true
g_reg_every: 4
gan_mode: softplus
image_dir: /root/datasets_ssd/zillow/
init_type: null
init_variance: 0.02
isTrain: true
lambda_l1: 1.0
lambda_vgg: 10.0
list_dir: null
load_from_opt_file: false
load_pretrained_d: null
load_pretrained_g: null
load_pretrained_g_ema: null
load_size: 128
lr: 0.002
mask_dir: /root/datasets_ssd/zillow/tripod_masks
max_dataset_size: 9223372036854775807
mbstd_group_size: 4
mbstd_num_features: 1
mixing: 0.0
model: comod
nThreads: 1
name: comod_places
netD: comodgan
netG: comodgan
niter: 50
niter_decay: 0
no_flip: false
no_g_reg: false
no_l1_loss: false
no_vgg_loss: false
noise_injection: true
nonlinearity: lrelu
num_channels: 3
optimizer: adam
output_dir: ./zillow
output_nc: 3
path_batch_shrink: 2
path_objectshape_base: null
path_objectshape_list: null
path_regularize: 2
phase: train
pix2pix: false
preprocess_mode: resize
print_freq: 101
r1: 10
randomize_noise: true
resample_kernel:
- 1
- 3
- 3
- 1
save_epoch_freq: 10
save_latest_freq: 50000
save_remote_gs: null
serial_batches: false
style_mod: true
trainer: stylegan2
truncation: null
validation_freq: 50000
which_epoch: latest
z_dim: 512
